### ISSUE TITLE
SpamAssassin/DKIM filter kills smtpd

### ISSUE THREAD

**Issue by hrkfdn** [OpenSMTPD/OpenSMTPD#619]
Heya,

I'm using 5.7.1 with two filters from -extras on OpenBSD 5.7 with the following configuration:
> filter dkim dkim-signer "-p/etc/ssl/private/dkim.key" "-daffekt.org"
> filter sa spamassassin "-s accept"
> filter myfilters chain dkim sa
> 
> listen on vio0 port 25 tls pki mail.affekt.org auth-optional hostname "mail.affekt.org" filter myfilters
> listen on vio0 smtps pki mail.affekt.org auth-optional hostname "mail.affekt.org" filter myfilters

This works great. After a while, however, the filter closes causing smtpd to shut down. This is not so great, as I don't immediately notice it and I could lose mail, should I not notice it at all.

In such situations, the log states the following: https://paste.xinu.at/m-Iyda6S/ (link to two occurrences)

Any more input I can help with?

Henrik

**Comment by poolpOrg** [comment]
I contacted Joerg so he has a look at this, waiting for feedback.

**Comment by hrkfdn** [comment]
It just happened again, though this time triggered by the dkim filter. Maybe it is actually a problem of the filtering system and not the filters itself?

Log: https://paste.xinu.at/a6Zv/

**Comment by snimmagadda** [comment]
Could you reproduce the crash reliably? It would help if you could gather coredumps when it happens again. As you are using OpenBSD 5.7, you could follow the last example in sysctl(8) with kern.nosuidcoredump=3 and share the tracebacks.

**Comment by hrkfdn** [comment]
I forgot to mention that I changed the order of the filter chain to:
filter myfilters chain sa dkim

No, unfortunately not, it just happens after a few days/weeks. I have set the sysctl accordingly and will report back once it happens again.

**Comment by hrkfdn** [comment]
So it just happened again: https://paste.xinu.at/5SJH/

I could not find any coredumps, though. Should there be any? On first sight it looks like a well-controlled shutdown.

**Comment by snimmagadda** [comment]
Yes, it's a controlled shutdown on an exceptional event i.e., filter process died. Hope you have created /var/crash/smtpd with chmod 700 as described in the manpage otherwise coredumps wouldn't be saved.

**Comment by hrkfdn** [comment]
I have. However there was nothing there.. Anything else I can do that helps?

**Comment by snimmagadda** [comment]
Lack of coredumps might be because of a graceful exit from an err() in the filters as Joerg points out in his response. Joerg's comments in a private email for this thread as he isn't on Github...

"Currently, filter errors are not sent to syslog, so hard to find the offending err(). You should run with debug console on and with tracing enabled. If possible could you try to make the problem reproduce-able for e.g find the incoming mail which triggers the problem.

 Importantly, could you also increase spamassassin, spamd debug levels and see any problems in the logs, it could likely be a problem there as well.

Which spamassassin version are you running?"

**Comment by hrkfdn** [comment]
It hasn't crashed yet, but I just observed that some mails are getting lost. Unfortunately I haven't set Spamassassin to be more verbose (version 3.4.0 from 5.7 by the way), but I have smtpd traces: https://paste.xinu.at/m-vYLrVw/

I have successfully received emails after this incident. I will restart spamd now with verbose logging.

**Comment by hrkfdn** [comment]
So that last [mail](http://marc.info/?l=openbsd-misc&m=144085063727363&w=2) has been resent to me, as my smtpd never accepted it, and it resulted in the same error.

**Comment by hrkfdn** [comment]
Sorry for the noise, but here is some more input: The same mail getting lost, but with spamassassin spamd debug log this time (scroll down): https://paste.xinu.at/m-SxqQ/

**Comment by hrkfdn** [comment]
And a log of a crash: https://paste.xinu.at/m-ZfznsM/

**Comment by hrkfdn** [comment]
So this keeps happening. And it keeps happening regardless of the filter, as it crashes with the DKIM and SpamAssassin filters.

Is there anything else I can provide? I've noticed that the longer traces went offline, do you want me to provide new debug/trace logs?

I would really love to assist in getting this fixed, as I constantly need to check if smtpd has crashed to not miss any mails.

**Comment by snimmagadda** [comment]
Could you please provide the logs again, preferably somewhere that could retain it a bit longer (or a mail to misc).

**Comment by hrkfdn** [comment]
Here is a tracelog with the DKIM filter crashing: http://affekt.org/logs/smtpd_dkim.txt

**Comment by snimmagadda** [comment]
Could you try this diff against latest OpenSMTPD-extras repo...
https://poolp.org/~sunil/619.diff

**Comment by hrkfdn** [comment]
Thanks, just applied this. Will let you know how it's going.

**Comment by hrkfdn** [comment]
It crashed again. Unfortunately I only have this short log:
http://affekt.org/logs/smtpd_crash2.txt

I'll try and get another one should it occur again.

**Comment by hrkfdn** [comment]
And another, more detailled crashlog: https://affekt.org/logs/smtpd_crash3.txt

**Comment by snimmagadda** [comment]
Could you try with the current OpenSMTPD and OpenSMTPD-extras. There are a couple of commits that help in logging from filters. Note that DKIM-Signer arguments changed slightly. The "domain" argument now needs to use "-D". refer filter-dkim-signer(8).

**Comment by hrkfdn** [comment]
Current as in CVS/Git HEAD? Sure. Do you want me to reapply the patch you posted here?

**Comment by snimmagadda** [comment]
Git HEAD, and yes, all the patches have been committed.

**Comment by hrkfdn** [comment]
Here is another crashlog: https://affekt.org/logs/smtpd_crash4.txt

Also I had to apply this: https://github.com/OpenSMTPD/OpenSMTPD-extras/pull/23

**Comment by hrkfdn** [comment]
Two more:
https://affekt.org/logs/smtpd_crash5.txt
https://affekt.org/logs/smtpd_crash6.txt

Any indication on what could be the issue? Anything else I can provide that would help?

**Comment by hrkfdn** [comment]
And here's a new one. Connection limit reached: http://affekt.org/logs/smtpd_client_limit.txt

**Comment by hrkfdn** [comment]
Unfortunately this is still an issue. I am running an OpenSMTPD build with extras from January 18th. Am I the only one experiencing this? Surely there must be more people playing around with the filters :P

**Comment by crepererum** [comment]
@hrkfdn I have the similar problem (no spamassasin, only the dkim filter) but didn't had enough time for proper debugging because I need the server in a proper state.

**Comment by hrkfdn** [comment]
Yeah, I can confirm that this happens with single filters as well.

**Comment by poolpOrg** [comment]
fwiw @ericfaurot and jung are working on filters so you may want to check with snapshots on a regular basis, at least 4 cleanups and bug fixes were made in the filters layer in the last few days and some are part of the snapshot I published yesterday.

**Comment by hrkfdn** [comment]
That's great! I will give git HEAD a try :)

**Comment by poolpOrg** [comment]
jung@ says that the issue should be fixed, however you need to update both smtpd AND extras, not only smtpd.

please confirm so we can close this ticket and make the PR fit in a single page again ;-)

**Comment by hrkfdn** [comment]
Already running latest smtpd and extras, very excited ;)

Well it took up to a few weeks for the bug to show up, so why don't you close it for now to shrink that overview to a single page and if it shows up again I'll let you know? :)

**Comment by hrkfdn** [comment]
I'm afraid I am still encountering problems. This time it didn't crash, but the last email I received could not be processed ("spamassassin[13763]: warn: spamassassin -> filter: imsg_read: Resource temporarily unavailable") and after this I can not receive any more mails. Smtpd is still running, though.

Here's a log:
http://affekt.org/logs/smtpd_spamfilter.txt

**Comment by poolpOrg** [comment]
Does this still happen with the snapshot that was published yesterday or with the code in git ?

**Comment by hrkfdn** [comment]
Already running it. Will let you know when I know more.

**Comment by poolpOrg** [comment]
ok great, please let me know when you think this ticket can be closed ;-)

**Comment by poolpOrg** [comment]
ping ? :-)

**Comment by hrkfdn** [comment]
So far so good :) I'd like to wait 2-3 more days, as it sometimes took a little longer for the bug to show up, but it seems it's really fixed now.

Thanks for all the work, it's a great piece of software!

**Comment by poolpOrg** [comment]
no problem, please close the ticket when you're confident the issue has gone away ;)

**Comment by hrkfdn** [comment]
Awesome, still stable. I think it's fixed! :)

**Comment by hrkfdn** [comment]
Ugh, sorry about this. But today it crashed again :(

http://affekt.org/logs/smtpd_crash9.txt

**Comment by hrkfdn** [comment]
Something seems to be off in the filter/SA IPC:

E.g. after receiving a mail:
```
smtp: 0xea86522c000 (data): IO_LOWAT <io:0xea86522fae8 fd=170 to=-1 fl=W ib=0 ob=0>
smtp: 0xea86522c000: IO_DATAIN <io:0xea86522c048 fd=167 to=300000 fl=R ssl=TLSv1.2:ECDHE-RSA-CHACHA20-POLY1305:256 ib=3 ob=0>
<<< [EOM]
debug: smtp: 0xea86522c000: data io done (2251 bytes)
filter: new query QUERY_EOM
filter: filter_drain_query d7b6f8a5a54db145[QUERY_EOM,filter_session@0xea812bf9200[datalen=0,eom=0x0,ofile=0xea860a2c440]]
filter: running filter filter:spamassassin[hooks=0xffffffff,flags=0x0000] for query d7b6f8a5a54db145[QUERY_EOM,filter_session@0xea812bf9200[datalen=0,eom=0x0,ofile=0xea860a2c440]]
mproc: pony -> filter-proc : 28 IMSG_CTL_FAIL
filter: waiting for running query d7b6f8a5a54db145[QUERY_EOM,filter_session@0xea812bf9200[datalen=0,eom=0x0,ofile=0xea860a2c440]]
```

To which spamassassin logs:
```
Mar 03 11:50:16 ada spamd[14134]: spamd: connection from localhost [127.0.0.1]:42694 to port 783, fd 6
Mar 03 11:55:16 ada spamd[14134]: spamd: timeout: (300 second timeout while trying to PROCESS)
Mar 03 11:55:17 ada spamd[17742]: prefork: child states: II
```

However, this only seems to happen with some mails. This mail is in the queue of the sending host since March 1st. It's this mail: http://marc.info/?l=openbsd-misc&m=145687282311231&w=2
I'm guessing it'll be dropped soon and imagine that this has happened before.

At the same time I could send myself a mail which was processed fine. Maybe there is some mail termination sequence missing in the communication with the spamassassin daemon? Maybe some encoding/escaping problem as this mail seems to contain some odd characters.

Sending that message to myself via Gmail, it gets escaped differently (smtpd log):
`<<< [MSG] to get it on the device=C3=A2=E2=82=AC=C5=BD (not an easy task I believe).`

While this is how it arrived originally (C&Pd from terminal, could be missing the relevant characters):
`<<< [MSG] to get it on the device‎ (not an easy task I believe).`

Hope this helps.

**Comment by jdelic** [comment]
Just as a drive-by comment since I've read this issue while researching opensmtpd filters: 

[`â€Ž`](http://marc.info/?l=openbsd-misc&m=145687282311231&w=2) is `0xe2809e` which is a UTF-8 `DOUBLE LOW-9 QUOTATION MARK (U+201E)`. The Gmail representation is a double encoded representation based of Windows-1252 (0xc3a2e282acc5be). So, whatever fails between `spamd` and the opensmtpd filter is a result of this emails wrong encoding. I would start by looking at the email's MIME headers to figure out why nobody seems to be expecting UTF-8. 

That will hopefully lead to a reproducible test case.

**Comment by hrkfdn** [comment]
Experienced another crash with OpenSMTPD 5.9.1 on OpenBSD 5.9 with filters from packages:

http://affekt.org/logs/smtpd_crash10.txt
http://affekt.org/logs/smtpd_crash10_spamd.txt

**Comment by hrkfdn** [comment]
And another comment for the collection:

I've been using filter-dnsbl instead of filter-spamassassin for a few feeks and haven't experienced any crashes or other problems. This problem is probably limited to the SpamAssassin filter (encoding/escaping in IPC?).

**Comment by poolpOrg** [comment]
@hrkfdn any chance you could join IRC ?

**Comment by poolpOrg** [comment]
closing this ticket, we'll track in #698 from now on.

still waiting for feedback
