### ISSUE TITLE
Error compiling 6.6.0p1 with LibreSSL

### ISSUE THREAD

**Issue by ArchangeGabriel** [OpenSMTPD/OpenSMTPD#958]
On ArchLinux, with LibreSSL 3.0.2 and libasr 1.0.3:
```
gcc -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I../openbsd-compat/err_h -I/usr/include -D_FORTIFY_SOURCE=2  -march=x86-64 -mtune=generic -O2 -pipe -fno-plt  -fPIC -DPIC -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -I/usr/include/libressl -L/usr/lib/libressl -Wl,-rpath=/usr/lib/libressl -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o arc4random.o arc4random.c
arc4random.c:167:21: error: macro "arc4random_stir" passed 1 arguments, but takes just 0
  167 | arc4random_stir(void)
      |                     ^
In file included from includes.h:71,
                 from arc4random.c:27:
openbsd-compat.h:130: note: macro "arc4random_stir" defined here
  130 | # define arc4random_stir()
      | 
arc4random.c:168:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
  168 | {
      | ^
```

**Comment by ngortheone** [comment]
@ArchangeGabriel 

I have seen this here:
https://github.com/OpenSMTPD/OpenSMTPD/issues/944


> So, here is the problem, but I dunno how to fix it.
> 
> ./openbsd-compat/openbsd-compat.h
> 
> ```c
> #if defined(HAVE_ARC4RANDOM_STIR)
> void arc4random_stir(void);
> #elif defined(HAVE_ARC4RANDOM) || defined(LIBRESSL_VERSION_NUMBER)
> /* Recent system/libressl implementation; no need for explicit stir */
> # define arc4random_stir()
> #else
> /* openbsd-compat/arc4random.c provides arc4random_stir() */
> void arc4random_stir(void);
> #endif
> ```
> 
> ./openbsd-compat/arc4random.c
> 
> ```c
> void
> arc4random_stir(void)
> {
> 	_ARC4_LOCK();
> 	_rs_stir();
> 	_ARC4_UNLOCK();
> }
> ```
> 
> HAVE_ARC4RANDOM_STIR - not defined
> HAVE_ARC4RANDOM - not defined
> LIBRESSL_VERSION_NUMBER - defined!
> 
> so it results in mismatch between header definition and arc4random.c
> 
> ```
> /* Recent system/libressl implementation; no need for explicit stir */
> # define arc4random_stir()
> ```
> 
> vs
> 
> ```
> void
> arc4random_stir(void)
> ```

I bailed out and used openssl as I was not sure back th. But ultimately this has to be fixed.
@poolpOrg  - it looks like a bug in C code

**Comment by poolpOrg** [comment]
Indeed.

I'll have a look at it tomorrow as I'm exhausted and only capable of breaking things at this late hour :-)

I'm not too concerned because this can be solved in a p2 release very soon.

**Comment by ngortheone** [comment]
Hey @ArchangeGabriel 

Can you share your build script? What other libraries/dependencies are installed during the build?
I want to reproduce this problem. I was trying to reproduce it with docker (dockerfile here: https://github.com/OpenSMTPD/OpenSMTPD/pull/961) but to my surprise everything worked.

@poolpOrg noticeably we also do not have this problem on ubuntu ci build. So at the moment I don't know what is going on (different compiler version treat these situations differently?)

**Comment by ArchangeGabriel** [comment]
@ngortheone You can find it here (6.4.x): https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensmtpd.

They aren’t a lot of changes for 6.6, basically I’m just using the new `aliases` file that you’ve added instead of an empty one.

**Comment by ngortheone** [comment]
I tried clang and it actually gives much more helpful error message:
```
make[2]: Entering directory '/opensmtpd/openbsd-compat'
clang -DHAVE_CONFIG_H -I. -I..  -I../smtpd -I../openbsd-compat -I../openbsd-compat/err_h -I/usr/include   -g -O2  -fPIC -DPIC -Qunused-arguments -Wunknown-warning-option -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -fno-builtin-memset -D_BSD_SOURCE -D_DEFAULT_SOURCE  -c -o arc4random.o arc4random.c
arc4random.c:167:17: error: too many arguments provided to function-like macro invocation
arc4random_stir(void)
                ^
./openbsd-compat.h:130:10: note: macro 'arc4random_stir' defined here
# define arc4random_stir()
         ^
arc4random.c:167:1: error: variable has incomplete type 'void'
arc4random_stir(void)
^
arc4random.c:167:16: error: expected ';' after top level declarator
arc4random_stir(void)
               ^
               ;
3 errors generated.
``` 


@ArchangeGabriel 
https://github.com/OpenSMTPD/OpenSMTPD/pull/961#issuecomment-546742240
> You’re not building with LibreSSL that way, but with OpenSSL. Hence why it works.

This actually would make sense if libressl has some kind of compatibility layer that makes it look like openssl.

As far as I can see  that would be the only logical explanation why with libressl installed
it still builds on arch - only if `LIBRESSL_VERSION_NUMBER` was not picked up somehow.
This is the only way this macro can be expanded to a working code only if it goes to last else branch. 
```
#if defined(HAVE_ARC4RANDOM_STIR)
void arc4random_stir(void);
#elif defined(HAVE_ARC4RANDOM) || defined(LIBRESSL_VERSION_NUMBER)
/* Recent system/libressl implementation; no need for explicit stir */
# define arc4random_stir()
#else
/* openbsd-compat/arc4random.c provides arc4random_stir() */
void arc4random_stir(void);
#endif

```


And when I add this to config I can reproduce the problem:
```
--with-cflags='-I/usr/include/libressl -L/usr/lib/libressl -Wl,-rpath=/usr/lib/libressl'
```

**Comment by ArchangeGabriel** [comment]
LibreSSL definitively does have a compatibility layer that makes it looks like OpenSSL: that was initially the purpose, to have a drop-in replacement implementing the same API. That’s also why we need to namespace it for packaging, most libs/headers having the same name.

The totally different part of LibreSSL vs OpenSSL is libtls.

**Comment by ArchangeGabriel** [comment]
I think the issue here is the openbsd-compat layer not taking into account the fact that a non-OpenBSD system can have an up-to-date LibreSSL.

**Comment by ngortheone** [comment]
I also noticed that openbsd-compat layer duplicates libbsd and is still used when libbsd is installed... but that is probably a different issue too

I will leave this fix implementation to @poolpOrg, he should know better what needs to be done.

My simple solution seems to be working, but I am not sure about all possible consequences 
```diff
diff --git a/openbsd-compat/openbsd-compat.h b/openbsd-compat/openbsd-compat.h
index 451263b8..73a24050 100644
--- a/openbsd-compat/openbsd-compat.h
+++ b/openbsd-compat/openbsd-compat.h
@@ -127,7 +127,7 @@ unsigned int arc4random(void);
 void arc4random_stir(void);
 #elif defined(HAVE_ARC4RANDOM) || defined(LIBRESSL_VERSION_NUMBER)
 /* Recent system/libressl implementation; no need for explicit stir */
-# define arc4random_stir()
+void arc4random_stir(void);
 #else
 /* openbsd-compat/arc4random.c provides arc4random_stir() */
 void arc4random_stir(void);
```

**Comment by ArchangeGabriel** [comment]
This does not look like a fix though, pretty sure that wouldn’t work on OpenBSD (not even talking of possible consequences).

**Comment by ArchangeGabriel** [comment]
Actually, I’m wondering about a more general issue with compiling against LibreSSL, because in the whole log I also have messages like:
```
In file included from SSL_CTX_use_certificate_chain_mem.c:77:
/usr/include/libressl/openssl/ssl.h:508: warning: "SSL_OP_NO_CLIENT_RENEGOTIATION" redefined
  508 | #define SSL_OP_NO_CLIENT_RENEGOTIATION   0x00020000L
      | 
In file included from includes.h:71,
                 from SSL_CTX_use_certificate_chain_mem.c:63:
openbsd-compat.h:145: note: this is the location of the previous definition
  145 | #define SSL_OP_NO_CLIENT_RENEGOTIATION 0
      | 
SSL_CTX_use_certificate_chain_mem.c: In function ‘ssl_ctx_use_certificate_chain_bio’:
SSL_CTX_use_certificate_chain_mem.c:119:3: warning: implicit declaration of function ‘SSL_CTX_get_extra_chain_certs_only’; did you mean ‘SSL_CTX_get_extra_chain_certs’? [-Wimplicit-function-declaration]
  119 |   SSL_CTX_get_extra_chain_certs_only(ctx, &chain);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |   SSL_CTX_get_extra_chain_certs
At top level:
SSL_CTX_use_certificate_chain_mem.c:90:1: warning: ‘ssl_ctx_use_certificate_chain_bio’ defined but not used [-Wunused-function]
   90 | ssl_ctx_use_certificate_chain_bio(SSL_CTX *ctx, BIO *in)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

So I’m wondering if by enabling OpenSSL 1.1.x again, it did not add issues with LibreSSL…

**Comment by ngortheone** [comment]
yes, I see those too. Not sure how important this is, but definitely needs some triage.

**Comment by poolpOrg** [comment]
I will look into that issue this week, tomorrow hopefully.

**Comment by poolpOrg** [comment]
@ArchangeGabriel  assuming I setup an archlinux, how would I use your PKGBUILD ?

**Comment by ArchangeGabriel** [comment]
@poolpOrg Seems you removed your question, so I guess you find out by yourself?

**Comment by ngortheone** [comment]
@poolpOrg I think the easiest way to reproduce the issue is to trigger Actions Workflow. I have added a test case with Archlinux that exhibits the failure

**Comment by poolpOrg** [comment]
Then I misunderstood something because on Alpine the issue seems to be that it was using an older version of LibreSSL whereas here you're using 3.0.2.

Am I missing something ?

**Comment by ArchangeGabriel** [comment]
@poolpOrg No you’re right, I’m the one that missed that information. Then I guess it’s only Arch.

**Comment by ngortheone** [comment]
https://en.wikipedia.org/wiki/Void_Linux should be using LibreSSL by default.

**Comment by ngortheone** [comment]
https://repology.org/project/libressl/versions
Not a whole lot of distors have it, and those who do primarily have 2.9.x

**Comment by ArchangeGabriel** [comment]
Gentoo seems to be one possibility.

@poolpOrg Should I build against OpenSSL in the mean time?

**Comment by poolpOrg** [comment]
Can you try again the portable branch ?

It should build fine now :-)

**Comment by ArchangeGabriel** [comment]
It does build fine indeed, though they were some warnings ([full log](https://paste.xinu.at/O4c/)).

**Comment by ArchangeGabriel** [comment]
I also did an OpenSSL build for comparison ([log](https://paste.xinu.at/lDd/)), most warnings are common between the two. Exception are `SSL_OP_NO_CLIENT_RENEGOTIATION` ones (×19) as well as the `implicit declaration of function ‘SSL_CTX_get_extra_chain_certs_only` for LibreSSL versus four `warning: ‘ASN1_STRING_data’ is deprecated` for OpenSSL.

**Comment by poolpOrg** [comment]
Good, I'll let you test that the build works fine for you and close the issue if it does.

I'll address the warnings separately because a lot of them are understood and have no consequence, others like the deprecated functions are new to me but don't seem very impactful (particularly if you keep in mind that we do best effort OpenSSL but our real target is LibreSSL).

**Comment by ArchangeGabriel** [comment]
Awesome, then I’ll try the build later tonight and report. ;)

**Comment by ngortheone** [comment]
@ArchangeGabriel please feel free to open a new issue for warnings.

**Comment by poolpOrg** [comment]
Make it more generic though, it's not archlinux related but more of a general portable thing

**Comment by ArchangeGabriel** [comment]
Hum… smtpd exits 1 on start:
```
info: OpenSMTPD 6.6.0-portable starting
mproc: ca -> control: enabled
mproc: ca -> parent: enabled
mproc: ca -> pony: enabled
mproc: ca -> pony: disabled
ramstat: init
ramstat: set: uptime
ramstat: uptime: n/a -> n/a
mproc: control -> scheduler: enabled
mproc: control -> queue: enabled
mproc: control -> parent: enabled
mproc: control -> lka: enabled
mproc: control -> pony: enabled
mproc: control -> ca: enabled
mproc: pony -> parent: enabled
mproc: pony -> queue: enabled
mproc: pony -> lka: enabled
mproc: pony -> control: enabled
mproc: pony -> ca: enabled
mproc: scheduler -> control: enabled
mproc: scheduler -> queue: enabled
scheduler: getting batch: mask=0x3f, count=10
scheduler: got r=0, delay=-1, count=10
scheduler: sleeping
mproc: parent -> control: enabled
mproc: parent -> lka: enabled
mproc: parent -> queue: enabled
mproc: parent -> ca: enabled
mproc: parent -> pony: enabled
mproc: parent -> lka : 0 IMSG_CONF_START
mproc: parent -> lka : 0 IMSG_CONF_END
mproc: parent -> pony : 0 IMSG_CONF_START
mproc: parent -> pony : 0 IMSG_CONF_END
mproc: parent -> ca : 0 IMSG_CONF_START
mproc: parent -> ca : 0 IMSG_CONF_END
imsg: ca <- parent: IMSG_CONF_START (len=0)
imsg: ca <- parent: IMSG_CONF_END (len=0)
imsg: pony <- parent: IMSG_CONF_START (len=0)
imsg: pony <- parent: IMSG_CONF_END (len=0)
mproc: ca -> pony: enabled
mproc: lka -> parent: enabled
mproc: lka -> queue: enabled
mproc: lka -> control: enabled
mproc: lka -> pony: enabled
mproc: lka -> pony: disabled
imsg: lka <- parent: IMSG_CONF_START (len=0)
imsg: lka <- parent: IMSG_CONF_END (len=0)
mproc: lka -> pony: enabled
smtpd: process pony socket closed
```
Should I open a new ticket/try with OpenSSL?

**Comment by ngortheone** [comment]
If you have spare cycles please try OpenSSL too.
but I'd love to get LibreSSL issue solved.

Are you still building like this?
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/opensmtpd

What is in config file?

See if you can get more info with `-v` or trace
https://man.openbsd.org/smtpd

**Comment by ArchangeGabriel** [comment]
@ngortheone Yes, building like this. The diff:
```
-pkgver=6.4.2p1
+pkgver=6.6.0p1
```
```
 source=("https://www.opensmtpd.org/archives/${pkgname}-${pkgver}.tar.gz"
         opensmtpd.sysusers
         smtpd.service
-        smtpd.socket)
-sha256sums=('6d71155b15fa4ef0198d10dfb7b1905845c9d36d4a02321245a99da80002fb5d'
+        smtpd.socket
+        opensmtpd-6.6.0p1-libressl-portable.patch::"https://github.com/OpenSMTPD/OpenSMTPD/commit/b3b1a01719bb7c23c31eced0f8e8d4f7e35364b1.patch")
+sha256sums=('75a420941963a672b21fe6c820c51de07f1ac94a0d6d4aa4f7364124d85efce9'
             'b38b64f1457b7227d55585edc711cce525e089516d16b093e6c44387380e6b13'
             'abf5baeb2a87c60d668ad18ea41cc08cab7a4f76339dd6df05de15cdaadaf922'
-            '32d46de5562d01de445d04c93bcc9f94bf103539b676e449c32e3603a3866cf8')
+            '32d46de5562d01de445d04c93bcc9f94bf103539b676e449c32e3603a3866cf8'
+            '62a6717aad43d3b37139210bd02f4885df0877de1a1ab84877a13b3e95e2588d')
 install=${pkgname}.install
 
 prepare() {
-  sed -ri 's,/etc/mail,/etc/smtpd,g' "${pkgname}-${pkgver}/smtpd/smtpd.conf"
+  cd ${pkgname}-${pkgver}
+  sed -ri 's,/etc/mail,/etc/smtpd,g' smtpd/smtpd.conf
+  patch -Np1 -i ../opensmtpd-6.6.0p1-libressl-portable.patch
 }
```

I’ll get the verbose output and try OpenSSL right away.

**Comment by ArchangeGabriel** [comment]
Full log (with LibreSSL), partially anonymized:
```
# smtpd -d -v -T all
debug: init ssl-tree
info: loading pki information for domain1
info: loading pki information for domain2
info: loading pki information for domain3
info: loading pki information for domain4
info: loading pki information for domain5
info: loading pki information for helodomain
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for domain1
info: loading pki keys for domain2
info: loading pki keys for domain3
info: loading pki keys for domain4
info: loading pki keys for domain5
info: loading pki keys for helodomain
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
info: OpenSMTPD 6.6.0-portable starting
debug: init ssl-tree
info: loading pki information for domain1
info: loading pki information for domain2
info: loading pki information for domain3
debug: init ssl-tree
info: loading pki information for domain4
info: loading pki information for domain1
info: loading pki information for domain5
info: loading pki information for domain2
info: loading pki information for domain3
info: loading pki information for helodomain
info: loading pki information for domain4
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for domain1
info: loading pki information for domain5
info: loading pki information for helodomain
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for domain1
debug: init ssl-tree
info: loading pki keys for domain2
debug: init ssl-tree
info: loading pki information for domain1
debug: init ssl-tree
info: loading pki keys for domain2
info: loading pki information for domain2
info: loading pki information for domain1
info: loading pki information for domain3
info: loading pki information for domain1
info: loading pki information for domain4
info: loading pki keys for domain3
info: loading pki keys for domain3
info: loading pki information for domain2
info: loading pki information for domain2
info: loading pki information for domain3
info: loading pki information for domain3
info: loading pki information for domain4
info: loading pki keys for domain4
info: loading pki keys for domain4
info: loading pki information for domain5
info: loading pki information for domain4
info: loading pki information for helodomain
info: loading pki information for domain5
debug: init ca-tree
info: loading pki information for helodomain
debug: init ssl-tree
info: loading pki keys for domain1
debug: init ca-tree
debug: init ssl-tree
info: loading pki information for domain5
info: loading pki information for domain1
info: loading pki keys for domain5
info: loading pki keys for domain5
info: loading pki information for helodomain
info: loading pki information for domain2
info: loading pki information for domain3
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for domain1
info: loading pki information for domain4
info: loading pki information for domain5
info: loading pki keys for helodomain
info: loading pki keys for helodomain
info: loading pki keys for domain2
info: loading pki information for helodomain
debug: init ca-tree
debug: init ssl-tree
info: loading pki keys for domain1
info: loading pki keys for domain2
debug: using "fs" queue backend
debug: using "fs" queue backend
info: loading pki keys for domain3
debug: using "ramqueue" scheduler backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
debug: using "ram" stat backend
info: loading pki keys for domain3
info: loading pki keys for domain2
info: loading pki keys for domain4
setup_peer: control -> klondike[93106] fd=4
setup_peer: klondike -> control[93107] fd=4
info: loading pki keys for domain4
setup_peer: control -> lookup[93108] fd=5
info: loading pki keys for domain3
setup_peer: klondike -> pony express[93109] fd=5
info: loading pki keys for domain5
setup_peer: control -> pony express[93109] fd=6
info: loading pki keys for domain5
info: loading pki keys for domain4
info: loading pki keys for helodomain
setup_proc: klondike done
setup_peer: control -> queue[93110] fd=7
info: loading pki keys for helodomain
debug: using "fs" queue backend
info: loading pki keys for domain5
debug: using "ramqueue" scheduler backend
setup_done: ca[93106] done
debug: using "ram" stat backend
setup_peer: control -> scheduler[93111] fd=8
mproc: ca -> control: enabled
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
mproc: ca -> parent: enabled
mproc: ca -> pony: enabled
info: loading pki keys for helodomain
setup_peer: lookup -> control[93107] fd=4
mproc: ca -> pony: disabled
debug: init ssl-tree
info: loading pki keys for domain1
setup_proc: control done
setup_peer: pony express -> control[93107] fd=4
setup_peer: lookup -> pony express[93109] fd=5
setup_done: control[93107] done
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
debug: using "ram" stat backend
setup_peer: pony express -> klondike[93106] fd=5
setup_peer: lookup -> queue[93110] fd=6
ramstat: init
ramstat: set: uptime
ramstat: uptime: n/a -> n/a
setup_peer: queue -> control[93107] fd=4
info: loading pki keys for domain2
setup_peer: pony express -> lookup[93108] fd=6
mproc: control -> scheduler: enabled
setup_proc: lookup done
mproc: control -> queue: enabled
mproc: control -> parent: enabled
setup_peer: queue -> pony express[93109] fd=5
mproc: control -> lka: enabled
mproc: control -> pony: enabled
mproc: control -> ca: enabled
setup_peer: pony express -> queue[93110] fd=7
info: loading pki keys for domain3
setup_peer: queue -> lookup[93108] fd=6
setup_done: lka[93108] done
info: loading pki keys for domain4
setup_peer: queue -> scheduler[93111] fd=7
setup_proc: pony express done
info: loading pki keys for domain5
setup_done: pony[93109] done
setup_proc: queue done
info: loading pki keys for helodomain
mproc: pony -> parent: enabled
mproc: pony -> queue: enabled
mproc: pony -> lka: enabled
mproc: pony -> control: enabled
mproc: pony -> ca: enabled
debug: rsa_engine_init: using RSA privsep engine
debug: ecdsa_engine_init: using ECDSA privsep engine
debug: using "fs" queue backend
debug: using "ramqueue" scheduler backend
setup_done: queue[93110] done
debug: using "ram" stat backend
setup_peer: scheduler -> control[93107] fd=4
setup_peer: scheduler -> queue[93110] fd=5
setup_proc: scheduler done
debug: bounce warning after 4h
setup_done: scheduler[93111] done
smtpd: setup done
mproc: scheduler -> control: enabled
mproc: scheduler -> queue: enabled
mproc: parent -> control: enabled
mproc: parent -> lka: enabled
scheduler: getting batch: mask=0x3f, count=10
debug: /--- ramqueue: scheduler_ram_batch()
mproc: parent -> queue: enabled
debug: \---
scheduler: got r=0, delay=-1, count=10
mproc: parent -> ca: enabled
scheduler: sleeping
mproc: parent -> pony: enabled
debug: parent_send_config_ruleset: reloading
mproc: parent -> lka : 0 IMSG_CONF_START
mproc: parent -> lka : 0 IMSG_CONF_END
debug: parent_send_config: configuring pony process
mproc: parent -> pony : 0 IMSG_CONF_START
mproc: parent -> pony : 0 IMSG_CONF_END
debug: parent_send_config: configuring ca process
mproc: parent -> ca : 0 IMSG_CONF_START
mproc: parent -> ca : 0 IMSG_CONF_END
imsg: pony <- parent: IMSG_CONF_START (len=0)
imsg: pony <- parent: IMSG_CONF_END (len=0)
debug: smtp: listen on 127.0.0.1 port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on [::1] port 25 flags 0x400 pki "" ca ""
debug: smtp: listen on publicIPv4 port 25 flags 0x401 pki "" ca ""
debug: smtp: listen on [publicIPv6] port 25 flags 0x401 pki "" ca ""
debug: smtp: listen on [privateIPv6] port 25 flags 0x401 pki "" ca ""
imsg: ca <- parent: IMSG_CONF_START (len=0)
debug: smtp: listen on publicIPv4 port 587 flags 0x54a pki "" ca ""
imsg: ca <- parent: IMSG_CONF_END (len=0)
debug: init private ssl-tree
debug: smtp: listen on [publicIPv6] port 587 flags 0x54a pki "" ca ""
debug: smtp: listen on [privateIPv6] port 587 flags 0x54a pki "" ca ""
debug: smtp: listen on 127.0.0.1 port 10028 flags 0x400 pki "" ca ""
debug: smtp: listen on [::1] port 10028 flags 0x400 pki "" ca ""
mproc: lka -> parent: enabled
mproc: lka -> queue: enabled
mproc: lka -> control: enabled
mproc: lka -> pony: enabled
mproc: lka -> pony: disabled
imsg: lka <- parent: IMSG_CONF_START (len=0)
imsg: lka <- parent: IMSG_CONF_END (len=0)
TABLE "<anydestination>" backend=static type=LIST
	"*"
TABLE "<anyhost>" backend=static type=LIST
	"0.0.0.0/0"
	"::/0"
	"local"
TABLE "<dynamic:0>" backend=static type=LIST
	"dkim_out"
TABLE "<dynamic:1>" backend=static type=LIST
	"smtp://127.0.0.1:10027"
TABLE "<getpwnam>" backend=getpwnam type=DYNAMIC
TABLE "<localhost>" backend=static type=LIST
	"127.0.0.1"
	"publicIPv4"
	"[publicIPv6]"
	"[::1]"
	"[privateIPv6]"
	"local"
TABLE "<localnames>" backend=static type=LIST
	"127.0.0.1"
	"publicIPv4"
	"[127.0.0.1]"
	"[publicIPv6]"
	"[publicIPv4]"
	"[::1]"
	"[[publicIPv6]]"
	"[[::1]]"
	"[[privateIPv6]]"
	"[privateIPv6]"
	"[ipv6:[publicIPv6]]"
	"[ipv6:[::1]]"
	"[ipv6:[privateIPv6]]"
	"localhost"
	"valinor"
TABLE "aliases" backend=static type=HASH config="/etc/smtpd/aliases"
	"myuser" -> "myuseremail"
	"root" -> "myuser"
mproc: ca -> pony: enabled
	"vmail" -> "/dev/null"
TABLE "passwd" backend=static type=HASH config="/etc/smtpd/passwd"
	"user1" -> "passwdhash1"
    …
	"usern" -> "passwdhashn"
TABLE "vdoms" backend=static type=LIST config="/etc/smtpd/vdoms"
	"domain1"
	"domain2"
	"domain3"
	"domain4"
	"domain5"
TABLE "vusers" backend=static type=HASH config="/etc/smtpd/vusers"
	<lots of content>
mproc: lka -> pony: enabled
debug: parent -> pony: pipe closed
debug: lka -> pony express: pipe closed
debug: lookup agent exiting
smtpd: process pony socket closed
debug: ca -> pony express: pipe closed
debug: ca agent exiting
debug: control -> pony express: pipe closed
debug: control agent exiting
debug: scheduler -> control: pipe closed
debug: scheduler agent exiting
```

**Comment by ArchangeGabriel** [comment]
It works with OpenSSL.

**Comment by flokli** [comment]
@ngortheone @ArchangeGabriel ran into the compilation problem as well.

NixOS unstable at 17574594e2634de65d1aa20887f4f66b92a41d2c, opensmtpd with libressl 3.0.2.
Building with openssl (1.1.1d) worked, see https://github.com/NixOS/nixpkgs/pull/72390.

**Comment by ngortheone** [comment]
@flokli this one was fixed just today. try pulling latest portable branch

**Comment by ngortheone** [comment]
@ArchangeGabriel will it work with libressl if you comment out the config sections that enable SSL? 

I suspect this is not a default config, but some kind of a prod system. Can you share anonymized config file - I will try to reproduce it myself and create a test case out of it.

**Comment by flokli** [comment]
was able to build with 276770264d398fc5a4671da2f31be832472e8b2d and libressl.

The [nixos opensmtpd vm tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/opensmtpd.nix) produced a segfault with the libressl version:

```
smtp2# smtpd[607]: setup_proc: scheduler done
smtp2# [   13.889216] smtpd[607]: debug: bounce warning after 4h
smtp2# [   13.893903] smtpd[607]: setup_done: scheduler[623] done
smtp2# [   13.915418] smtpd[607]: smtpd: setup done
smtp2# [   13.925239] smtpd[607]: debug: rsa_engine_init: using RSA privsep engine
smtp1# [   14.064768] smtpd[607]: debug: smtpd: scanning offline queue...
smtp1# [   14.066980] smtpd[607]: debug: smtpd: offline scanning done
smtp2# [   13.932476] smtpd[607]: debug: ecdsa_engine_init: using ECDSA privsep engine
smtp1# [   14.083731] systemd-logind[555]: Watching system buttons on /dev/input/event0 (AT Translated Set 2 keyboard)
smtp2# [   13.948578] smtpd[607]: debug: parent_send_config_ruleset: reloading
smtp1# [   14.102002] systemd-logind[555]: Watching system buttons on /dev/input/event2 (Power Button)
smtp1# [   14.223033] show_signal_msg: 58 callbacks suppressed
smtp1# [   14.223035] smtpd[614]: segfault at 7ffc8b969ff8 ip 0000000000451e1f sp 00007ffc8b96a000 error 6 in smtpd[407000+4f000]
smtp2# [   13.965366] smtpd[607]: debug: parent_send_config: configuring pony process
smtp1# [   14.226498] Code: 06 05 00 ba 28 00 00 00 0f 29 05 2c 06 05 00 e9 6b ff ff ff 0f 1f 80 00 00 00 00 41 57 41 56 41 55 49 89 fd 41 54 55 48 89 f5 <53> 48 83 ec 08 e8 d7 58 fb ff 48 8b 15 d0 05 05 00 48 39 d5 73 0e
smtp2# [   13.990218] smtpd[607]: debug: parent_send_config: configuring ca process
smtp1# [   14.131590] smtpd[607]: debug: lka -> pony express: pipe closed
smtp1# [   14.135013] smtpd[607]: debug: lookup agent exiting
smtp2# [   13.997747] smtpd[607]: debug: smtp: listen on 0.0.0.0 port 25 flags 0x400 pki "" ca ""
smtp1# [   14.138067] smtpd[607]: debug: control -> lookup: pipe closed
smtp1# [   14.142501] smtpd[607]: debug: control agent exiting
smtp2# [   14.013165] smtpd[607]: debug: smtp: will accept at most 262139 clients
smtp1# [   14.149666] smtpd[607]: debug: parent -> lka: pipe closed
smtp1# [   14.157347] smtpd[607]: smtpd: process lka socket closed
smtp1# [   14.163187] smtpd[607]: debug: scheduler -> control: pipe closed
smtp1# [   14.168519] smtpd[607]: debug: scheduler agent exiting
smtp1# [   14.174110] systemd[1]: opensmtpd.service: Main process exited, code=exited, status=1/FAILURE
smtp2# [   14.038418] dovecot[615]: imap-login: Disconnected (disconnected before auth was ready, waited 0 secs): user=<>, rip=::1, lip=::1, secured, session=<nASpND6WfJQAAAAAAAAAAAAAAAAAAAAB>
smtp1# [   14.182592] smtpd[607]: debug: ca -> control: pipe closed
smtp1# [   14.190031] smtpd[607]: debug: ca agent exiting
smtp2# [   14.063485] smtpd[607]: setup_proc: klondike done
smtp2# [   14.078649] smtpd[607]: debug: init private ssl-tree
smtp2# [   14.092865] smtpd[607]: debug: smtpd: scanning offline queue...
smtp2# [   14.104316] smtpd[607]: debug: smtpd: offline scanning done
smtp2# [   14.318819] show_signal_msg: 74 callbacks suppressed
smtp2# [   14.318821] smtpd[619]: segfault at 7ffe86954ff8 ip 0000000000451e24 sp 00007ffe86955000 error 6 in smtpd[407000+4f000]
smtp2# [   14.329064] Code: 00 00 00 0f 29 05 2c 06 05 00 e9 6b ff ff ff 0f 1f 80 00 00 00 00 41 57 41 56 41 55 49 89 fd 41 54 55 48 89 f5 53 48 83 ec 08 <e8> d7 58 fb ff 48 8b 15 d0 05 05 00 48 39 d5 73 0e 8b 0d 29 0a 05
smtp2# [   14.373931] ppdev: user-space parallel port driver
smtp2# [   14.246937] smtpd[607]: debug: lka -> pony express: pipe closed
smtp2# [   14.249178] smtpd[607]: debug: lookup agent exiting
smtp2# [   14.251137] smtpd[607]: debug: control -> lookup: pipe closed
smtp2# [   14.256396] smtpd[607]: debug: control agent exiting
smtp2# [   14.266545] smtpd[607]: debug: parent -> lka: pipe closed
smtp2# [   14.273264] smtpd[607]: smtpd: process lka socket closed
smtp1# [   14.412477] systemd-vconsole-setup[618]: KD_FONT_OP_GET failed while trying to get the font metadata: Input/output error
```

When linking against openssl (1.1.1d) the tests passed.

**Comment by ArchangeGabriel** [comment]
@ngortheone The config:
```
pki heloname cert "/etc/smtpd/tls/heloname.crt"
pki heloname key "/etc/smtpd/tls/heloname.key"
pki domain1 cert "/etc/smtpd/tls/domain1.crt"
pki domain1 key "/etc/smtpd/tls/domain1.key"
pki domain5 cert "/etc/smtpd/tls/domain5.crt"
pki domain5 key "/etc/smtpd/tls/domain5.key"
pki domain4 cert "/etc/smtpd/tls/domain4.crt"
pki domain4 key "/etc/smtpd/tls/domain4.key"
pki domain3 cert "/etc/smtpd/tls/domain3.crt"
pki domain3 key "/etc/smtpd/tls/domain3.key"
pki domain2 cert "/etc/smtpd/tls/domain2.crt"
pki domain2 key "/etc/smtpd/tls/domain2.key"

# List of aliases for system users
table aliases   file:/etc/smtpd/aliases
# Passwd file for users credentials
table passwd    file:/etc/smtpd/passwd
# List of domains for which to accept emails
table vdoms     file:/etc/smtpd/vdoms
# List of existing email adresses and their aliases
table vusers    file:/etc/smtpd/vusers

# Accept local connections from system users
listen on lo port 25
# Accept connections from outside for delivering emails to local users (no tls-require [verify] because some servers fail those)
listen on enp1s0f0 port 25 hostname heloname tls
# Accept connections from authenticated users to send emails
listen on enp1s0f0 port 587 hostname heloname smtps auth <passwd> mask-src
# Get back DKIM signed emails
listen on lo port 10028 tag DKIM_OUT

# Deliver local messages
action "local" lmtp "/var/run/dovecot/lmtp" rcpt-to alias <aliases>
match for local action "local"

# Deliver incoming emails (that passed rDNS test) for local users
action "inbox" lmtp "/var/run/dovecot/lmtp" rcpt-to virtual <vusers>
match from rdns for domain <vdoms> action "inbox"

# Send DKIM signed emails to the world (no tls [verify] because some servers fail this)
action "outbound" relay helo heloname
match tag DKIM_OUT for any action "outbound"

# Send outgoing emails to DKIM
action "dkim" relay host smtp://127.0.0.1:10027
match auth from any for any action "dkim"
```

But now that @flokli mentions it, I also have segfaults in dmesg for the libressl case.

**Comment by ArchangeGabriel** [comment]
Segfaults are either `in smtpd` or `in libcrypto.so.45.0.5`.

**Comment by ngortheone** [comment]
This is helpful, thanks guys

I will try to reproduce it myself. And maybe create debug build to see  where it fails with gdb.

@flokli 
I am not a nix expert, can you explain how your test case is working? I want to see if I can incorporate it in our CI system

**Comment by ArchangeGabriel** [comment]
I have another issue (with OpenSSL), which is I can’t send mails to the outside (I get `550 Invalid recipient:` errors). I suppose this is unrelated, but asking there first just in case.

**Comment by flokli** [comment]
@ngortheone I pushed my WIP to https://github.com/flokli/nixpkgs/tree/opensmtpd-debug, and a version with debug symbols for opensmtpd and libressl to https://github.com/flokli/nixpkgs/tree/opensmtpd-debug.

Basically, Nix from https://nixos.org needs to be installed, then you can run `nix-build nixos/tests/opensmtpd.nix` from inside the checkout root.

You can also run `nix-build nixos/tests/opensmtpd.nix -A driver && result/bin/nixos-test-driver`, and issue `$smtp1->start()` to interactively get a qemu vm with that config.

`coredumpctl debug` should give you the following stacktrace:
![image](https://user-images.githubusercontent.com/183879/67995598-8b389a00-fc4b-11e9-82c7-a23b6db9e68a.png)

**Comment by ngortheone** [comment]
Ok, this looks like something that @poolpOrg did not quite fix today :)
We will need to wait for him to fix this

**Comment by flokli** [comment]
Feel free to ping me once there's something new to test - also joined the IRC-Channel.

**Comment by ArchangeGabriel** [comment]
Also, smtpd segfaults (in libc-2.30.so this time) upon receiving a valid connection on port 25, on the OpenSSL build… But this seems related to the `from rdns` new setting, reverting to `from any` works. So I guess new issue for this?

**Comment by ngortheone** [comment]
yes please

**Comment by ArchangeGabriel** [comment]
Note, I’m reverting my setup to 6.4, since after disabling rdns the test email was accepted from one of my external email address but `550 Invalid recipient` rejected from another one…

**Comment by poolpOrg** [comment]
> I have another issue (with OpenSSL), which is I can’t send mails to the outside (I get `550 Invalid recipient:` errors). I suppose this is unrelated, but asking there first just in case.

that's unrelated, the invalid recipient is likely caused by the ruleset, try smtpd -dv -T rules to see if it has matched the right rule or none at all.

I'm looking into the crash, it's weird that I don't get a reliable behavior across distros :-/

**Comment by ngortheone** [comment]
@ArchangeGabriel, @flokli
We have a potential fix in branch `test-ssl-bugfix`, I did some light testing and it does not crash for me.
I did not have much time today to do proper testing. Could you test it?

**Comment by ngortheone** [comment]
Just in case: more similar logs and configs here https://github.com/OpenSMTPD/OpenSMTPD/issues/908#issue-412213569

**Comment by poolpOrg** [comment]
This ticket has grown a bit unmanageable as it mixes multiple issues somewhat unrelated.

The original issue was the compilation failure with LibreSSL, this got fixed with a commit made to the test-ssl-bugfix branch to properly escape the arc4random_stir() function when not needed. With the compilation succeeding, it exposed another escaping issue which could cause crashes depending on the setup you have (system arc4random vs OpenSSL + compat vs LibreSSL + compat), this was also fixed in the test-ssl-bugfix branch and I merged the branch to portable because, even if we happen to find other issues around here, this is still the right way forward.

With that being said I'll close the ticket because:

- original issue with compilation error is fixed, there's no longer problems with that
- segv experienced by @flokli is very likely fixed and otherwise a new specific issue can be opened
- from rdns had a specific issue opened (#969) which I have also fixed
- warnings have specific tickets (#965, #966, #967) I fixed two of them and have assessed the other one
- the remaining segv experienced by @ArchangeGabriel has a ticket #968 which is being worked on

**Comment by flokli** [comment]
@poolpOrg I can confirm the segv i experienced was fixed. Thanks a lot!
